// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file proto/core/v1/stock.proto (package proto.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/core/v1/stock.proto.
 */
export const file_proto_core_v1_stock: GenFile =
	/*@__PURE__*/
	fileDesc(
		"Chlwcm90by9jb3JlL3YxL3N0b2NrLnByb3RvEg1wcm90by5jb3JlLnYxIn8KBVN0b2NrEg8KAmlkGAEgASgNSACIAQESDAoEbmFtZRgCIAEoCRIQCghxdWFudGl0eRgDIAEoBRIrCgpjYXRlZ29yaWVzGAQgAygLMhcucHJvdG8uY29yZS52MS5DYXRlZ29yeRIRCglpbWFnZV91cmwYBSABKAlCBQoDX2lkIjAKCENhdGVnb3J5Eg8KAmlkGAEgASgNSACIAQESDAoEbmFtZRgCIAEoCUIFCgNfaWRChAEKEWNvbS5wcm90by5jb3JlLnYxQgpTdG9ja1Byb3RvUAFaDXByb3RvL2NvcmUvdjGiAgNQQ1iqAg1Qcm90by5Db3JlLlYxygINUHJvdG9cQ29yZVxWMeICGVByb3RvXENvcmVcVjFcR1BCTWV0YWRhdGHqAg9Qcm90bzo6Q29yZTo6VjFiBnByb3RvMw",
	);

/**
 * @generated from message proto.core.v1.Stock
 */
export type Stock = Message<"proto.core.v1.Stock"> & {
	/**
	 * @generated from field: optional uint32 id = 1;
	 */
	id?: number;

	/**
	 * @generated from field: string name = 2;
	 */
	name: string;

	/**
	 * @generated from field: int32 quantity = 3;
	 */
	quantity: number;

	/**
	 * @generated from field: repeated proto.core.v1.Category categories = 4;
	 */
	categories: Category[];

	/**
	 * @generated from field: string image_url = 5;
	 */
	imageUrl: string;
};

/**
 * Describes the message proto.core.v1.Stock.
 * Use `create(StockSchema)` to create a new message.
 */
export const StockSchema: GenMessage<Stock> =
	/*@__PURE__*/
	messageDesc(file_proto_core_v1_stock, 0);

/**
 * @generated from message proto.core.v1.Category
 */
export type Category = Message<"proto.core.v1.Category"> & {
	/**
	 * @generated from field: optional uint32 id = 1;
	 */
	id?: number;

	/**
	 * @generated from field: string name = 2;
	 */
	name: string;
};

/**
 * Describes the message proto.core.v1.Category.
 * Use `create(CategorySchema)` to create a new message.
 */
export const CategorySchema: GenMessage<Category> =
	/*@__PURE__*/
	messageDesc(file_proto_core_v1_stock, 1);
