// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file proto/core/v1/stock.proto (package proto.core.v1, syntax proto3)
 

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/core/v1/stock.proto.
 */
export const file_proto_core_v1_stock: GenFile = /*@__PURE__*/
  fileDesc("Chlwcm90by9jb3JlL3YxL3N0b2NrLnByb3RvEg1wcm90by5jb3JlLnYxImAKBVN0b2NrEgoKAmlkGAEgASgNEgwKBG5hbWUYAiABKAkSEAoIcXVhbnRpdHkYAyABKAUSKwoKY2F0ZWdvcmllcxgEIAMoCzIXLnByb3RvLmNvcmUudjEuQ2F0ZWdvcnkiJAoIQ2F0ZWdvcnkSCgoCaWQYASABKA0SDAoEbmFtZRgCIAEoCUKEAQoRY29tLnByb3RvLmNvcmUudjFCClN0b2NrUHJvdG9QAVoNcHJvdG8vY29yZS92MaICA1BDWKoCDVByb3RvLkNvcmUuVjHKAg1Qcm90b1xDb3JlXFYx4gIZUHJvdG9cQ29yZVxWMVxHUEJNZXRhZGF0YeoCD1Byb3RvOjpDb3JlOjpWMWIGcHJvdG8z");

/**
 * @generated from message proto.core.v1.Stock
 */
export type Stock = Message<"proto.core.v1.Stock"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 quantity = 3;
   */
  quantity: number;

  /**
   * @generated from field: repeated proto.core.v1.Category categories = 4;
   */
  categories: Category[];
};

/**
 * Describes the message proto.core.v1.Stock.
 * Use `create(StockSchema)` to create a new message.
 */
export const StockSchema: GenMessage<Stock> = /*@__PURE__*/
  messageDesc(file_proto_core_v1_stock, 0);

/**
 * @generated from message proto.core.v1.Category
 */
export type Category = Message<"proto.core.v1.Category"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message proto.core.v1.Category.
 * Use `create(CategorySchema)` to create a new message.
 */
export const CategorySchema: GenMessage<Category> = /*@__PURE__*/
  messageDesc(file_proto_core_v1_stock, 1);

