version: 2
updates:
  # Enable version updates for npm (Next.js frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - frontend
      - dependencies
    groups:
      connect:
        patterns:
          - "@connect*"
          - "@bufbuild*"
      next:
        patterns:
          - "next*"
      react:
        patterns:
          - "react*"
      prettier:
        patterns:
          - "prettier*"
      materialUI:
        patterns:
          - "@mui*"
          - "@emotion*"
      all:
        patterns:
          - "*"

  # Enable version updates for Go modules (backend)
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - backend
      - dependencies
    groups:
      all:
        patterns:
          - "*"

  # Enable version updates for Go modules (backend)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - github-actions
      - dependencies
    groups:
      all:
        patterns:
          - "*"
