// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/stock-o-matic-api/stock/repository.go
//
// Generated by this command:
//
//	mockgen -source=cmd/stock-o-matic-api/stock/repository.go -destination=cmd/stock-o-matic-api/tests/mocks/stock/stock_repository.go
//

// Package mock_stock is a generated GoMock package.
package mock_stock

import (
	context "context"
	reflect "reflect"

	corev1 "github.com/DarylvdBerg/stock-o-matic/internal/proto/core/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// AddStock mocks base method.
func (m *MockIRepository) AddStock(ctx context.Context, data *corev1.Stock) (*corev1.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStock", ctx, data)
	ret0, _ := ret[0].(*corev1.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStock indicates an expected call of AddStock.
func (mr *MockIRepositoryMockRecorder) AddStock(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStock", reflect.TypeOf((*MockIRepository)(nil).AddStock), ctx, data)
}

// GetStock mocks base method.
func (m *MockIRepository) GetStock(ctx context.Context) ([]*corev1.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStock", ctx)
	ret0, _ := ret[0].([]*corev1.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStock indicates an expected call of GetStock.
func (mr *MockIRepositoryMockRecorder) GetStock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockIRepository)(nil).GetStock), ctx)
}

// UpdateStock mocks base method.
func (m *MockIRepository) UpdateStock(ctx context.Context, id uint32, data *corev1.Stock) (*corev1.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStock", ctx, id, data)
	ret0, _ := ret[0].(*corev1.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStock indicates an expected call of UpdateStock.
func (mr *MockIRepositoryMockRecorder) UpdateStock(ctx, id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStock", reflect.TypeOf((*MockIRepository)(nil).UpdateStock), ctx, id, data)
}
