// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/stock/core/stock.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Categories    []*Category            `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_proto_stock_core_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_core_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_proto_stock_core_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stock) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Stock) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_stock_core_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_core_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_stock_core_stock_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_stock_core_stock_proto protoreflect.FileDescriptor

const file_proto_stock_core_stock_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/stock/core/stock.proto\x12\n" +
	"proto.core\"}\n" +
	"\x05Stock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x124\n" +
	"\n" +
	"categories\x18\x04 \x03(\v2\x14.proto.core.CategoryR\n" +
	"categories\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\xa5\x01\n" +
	"\x0ecom.proto.coreB\n" +
	"StockProtoP\x01Z>github.com/DarylvdBerg/stock-o-matic/internal/proto/stock/core\xa2\x02\x03PCX\xaa\x02\n" +
	"Proto.Core\xca\x02\n" +
	"Proto\\Core\xe2\x02\x16Proto\\Core\\GPBMetadata\xea\x02\vProto::Coreb\x06proto3"

var (
	file_proto_stock_core_stock_proto_rawDescOnce sync.Once
	file_proto_stock_core_stock_proto_rawDescData []byte
)

func file_proto_stock_core_stock_proto_rawDescGZIP() []byte {
	file_proto_stock_core_stock_proto_rawDescOnce.Do(func() {
		file_proto_stock_core_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stock_core_stock_proto_rawDesc), len(file_proto_stock_core_stock_proto_rawDesc)))
	})
	return file_proto_stock_core_stock_proto_rawDescData
}

var file_proto_stock_core_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stock_core_stock_proto_goTypes = []any{
	(*Stock)(nil),    // 0: proto.core.Stock
	(*Category)(nil), // 1: proto.core.Category
}
var file_proto_stock_core_stock_proto_depIdxs = []int32{
	1, // 0: proto.core.Stock.categories:type_name -> proto.core.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stock_core_stock_proto_init() }
func file_proto_stock_core_stock_proto_init() {
	if File_proto_stock_core_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stock_core_stock_proto_rawDesc), len(file_proto_stock_core_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stock_core_stock_proto_goTypes,
		DependencyIndexes: file_proto_stock_core_stock_proto_depIdxs,
		MessageInfos:      file_proto_stock_core_stock_proto_msgTypes,
	}.Build()
	File_proto_stock_core_stock_proto = out.File
	file_proto_stock_core_stock_proto_goTypes = nil
	file_proto_stock_core_stock_proto_depIdxs = nil
}
