// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file proto/services/v1/category_service.proto (package proto.services.v1, syntax proto3)
 

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Category } from "../../core/v1/stock_pb";
import { file_proto_core_v1_stock } from "../../core/v1/stock_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/services/v1/category_service.proto.
 */
export const file_proto_services_v1_category_service: GenFile = /*@__PURE__*/
  fileDesc("Cihwcm90by9zZXJ2aWNlcy92MS9jYXRlZ29yeV9zZXJ2aWNlLnByb3RvEhFwcm90by5zZXJ2aWNlcy52MSIWChRHZXRDYXRlZ29yaWVzUmVxdWVzdCJEChVHZXRDYXRlZ29yaWVzUmVzcG9uc2USKwoKY2F0ZWdvcmllcxgBIAMoCzIXLnByb3RvLmNvcmUudjEuQ2F0ZWdvcnkiPwoSQWRkQ2F0ZWdvcnlSZXF1ZXN0EikKCGNhdGVnb3J5GAEgASgLMhcucHJvdG8uY29yZS52MS5DYXRlZ29yeSIVChNBZGRDYXRlZ29yeVJlc3BvbnNlIjEKFVVwZGF0ZUNhdGVnb3J5UmVxdWVzdBIKCgJpZBgBIAEoDRIMCgRuYW1lGAIgASgJIhgKFlVwZGF0ZUNhdGVnb3J5UmVzcG9uc2UyugIKD0NhdGVnb3J5U2VydmljZRJiCg1HZXRDYXRlZ29yaWVzEicucHJvdG8uc2VydmljZXMudjEuR2V0Q2F0ZWdvcmllc1JlcXVlc3QaKC5wcm90by5zZXJ2aWNlcy52MS5HZXRDYXRlZ29yaWVzUmVzcG9uc2USXAoLQWRkQ2F0ZWdvcnkSJS5wcm90by5zZXJ2aWNlcy52MS5BZGRDYXRlZ29yeVJlcXVlc3QaJi5wcm90by5zZXJ2aWNlcy52MS5BZGRDYXRlZ29yeVJlc3BvbnNlEmUKDlVwZGF0ZUNhdGVnb3J5EigucHJvdG8uc2VydmljZXMudjEuVXBkYXRlQ2F0ZWdvcnlSZXF1ZXN0GikucHJvdG8uc2VydmljZXMudjEuVXBkYXRlQ2F0ZWdvcnlSZXNwb25zZUKmAQoVY29tLnByb3RvLnNlcnZpY2VzLnYxQhRDYXRlZ29yeVNlcnZpY2VQcm90b1ABWhFwcm90by9zZXJ2aWNlcy92MaICA1BTWKoCEVByb3RvLlNlcnZpY2VzLlYxygIRUHJvdG9cU2VydmljZXNcVjHiAh1Qcm90b1xTZXJ2aWNlc1xWMVxHUEJNZXRhZGF0YeoCE1Byb3RvOjpTZXJ2aWNlczo6VjFiBnByb3RvMw", [file_proto_core_v1_stock]);

/**
 * Get categories
 *
 * @generated from message proto.services.v1.GetCategoriesRequest
 */
export type GetCategoriesRequest = Message<"proto.services.v1.GetCategoriesRequest"> & {
};

/**
 * Describes the message proto.services.v1.GetCategoriesRequest.
 * Use `create(GetCategoriesRequestSchema)` to create a new message.
 */
export const GetCategoriesRequestSchema: GenMessage<GetCategoriesRequest> = /*@__PURE__*/
  messageDesc(file_proto_services_v1_category_service, 0);

/**
 * @generated from message proto.services.v1.GetCategoriesResponse
 */
export type GetCategoriesResponse = Message<"proto.services.v1.GetCategoriesResponse"> & {
  /**
   * @generated from field: repeated proto.core.v1.Category categories = 1;
   */
  categories: Category[];
};

/**
 * Describes the message proto.services.v1.GetCategoriesResponse.
 * Use `create(GetCategoriesResponseSchema)` to create a new message.
 */
export const GetCategoriesResponseSchema: GenMessage<GetCategoriesResponse> = /*@__PURE__*/
  messageDesc(file_proto_services_v1_category_service, 1);

/**
 * Add category
 *
 * @generated from message proto.services.v1.AddCategoryRequest
 */
export type AddCategoryRequest = Message<"proto.services.v1.AddCategoryRequest"> & {
  /**
   * @generated from field: proto.core.v1.Category category = 1;
   */
  category?: Category;
};

/**
 * Describes the message proto.services.v1.AddCategoryRequest.
 * Use `create(AddCategoryRequestSchema)` to create a new message.
 */
export const AddCategoryRequestSchema: GenMessage<AddCategoryRequest> = /*@__PURE__*/
  messageDesc(file_proto_services_v1_category_service, 2);

/**
 * @generated from message proto.services.v1.AddCategoryResponse
 */
export type AddCategoryResponse = Message<"proto.services.v1.AddCategoryResponse"> & {
};

/**
 * Describes the message proto.services.v1.AddCategoryResponse.
 * Use `create(AddCategoryResponseSchema)` to create a new message.
 */
export const AddCategoryResponseSchema: GenMessage<AddCategoryResponse> = /*@__PURE__*/
  messageDesc(file_proto_services_v1_category_service, 3);

/**
 * Update category
 *
 * @generated from message proto.services.v1.UpdateCategoryRequest
 */
export type UpdateCategoryRequest = Message<"proto.services.v1.UpdateCategoryRequest"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message proto.services.v1.UpdateCategoryRequest.
 * Use `create(UpdateCategoryRequestSchema)` to create a new message.
 */
export const UpdateCategoryRequestSchema: GenMessage<UpdateCategoryRequest> = /*@__PURE__*/
  messageDesc(file_proto_services_v1_category_service, 4);

/**
 * @generated from message proto.services.v1.UpdateCategoryResponse
 */
export type UpdateCategoryResponse = Message<"proto.services.v1.UpdateCategoryResponse"> & {
};

/**
 * Describes the message proto.services.v1.UpdateCategoryResponse.
 * Use `create(UpdateCategoryResponseSchema)` to create a new message.
 */
export const UpdateCategoryResponseSchema: GenMessage<UpdateCategoryResponse> = /*@__PURE__*/
  messageDesc(file_proto_services_v1_category_service, 5);

/**
 * @generated from service proto.services.v1.CategoryService
 */
export const CategoryService: GenService<{
  /**
   * @generated from rpc proto.services.v1.CategoryService.GetCategories
   */
  getCategories: {
    methodKind: "unary";
    input: typeof GetCategoriesRequestSchema;
    output: typeof GetCategoriesResponseSchema;
  },
  /**
   * @generated from rpc proto.services.v1.CategoryService.AddCategory
   */
  addCategory: {
    methodKind: "unary";
    input: typeof AddCategoryRequestSchema;
    output: typeof AddCategoryResponseSchema;
  },
  /**
   * @generated from rpc proto.services.v1.CategoryService.UpdateCategory
   */
  updateCategory: {
    methodKind: "unary";
    input: typeof UpdateCategoryRequestSchema;
    output: typeof UpdateCategoryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_services_v1_category_service, 0);

