// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/stock/v1/stock_service.proto

package stockv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_stock_v1_stock_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_v1_stock_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_stock_v1_stock_service_proto_rawDescGZIP(), []int{0}
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_proto_stock_v1_stock_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_v1_stock_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_stock_v1_stock_service_proto_rawDescGZIP(), []int{1}
}

var File_proto_stock_v1_stock_service_proto protoreflect.FileDescriptor

const file_proto_stock_v1_stock_service_proto_rawDesc = "" +
	"\n" +
	"\"proto/stock/v1/stock_service.proto\x12\x0eproto.stock.v1\"\x11\n" +
	"\x0fGetStockRequest\"\x12\n" +
	"\x10GetStockResponse2]\n" +
	"\fStockService\x12M\n" +
	"\bGetStock\x12\x1f.proto.stock.v1.GetStockRequest\x1a .proto.stock.v1.GetStockResponseB\xc7\x01\n" +
	"\x12com.proto.stock.v1B\x11StockServiceProtoP\x01ZDgithub.com/DarylvdBerg/stock-o-matic/internal/proto/stock/v1;stockv1\xa2\x02\x03PSX\xaa\x02\x0eProto.Stock.V1\xca\x02\x0eProto\\Stock\\V1\xe2\x02\x1aProto\\Stock\\V1\\GPBMetadata\xea\x02\x10Proto::Stock::V1b\x06proto3"

var (
	file_proto_stock_v1_stock_service_proto_rawDescOnce sync.Once
	file_proto_stock_v1_stock_service_proto_rawDescData []byte
)

func file_proto_stock_v1_stock_service_proto_rawDescGZIP() []byte {
	file_proto_stock_v1_stock_service_proto_rawDescOnce.Do(func() {
		file_proto_stock_v1_stock_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stock_v1_stock_service_proto_rawDesc), len(file_proto_stock_v1_stock_service_proto_rawDesc)))
	})
	return file_proto_stock_v1_stock_service_proto_rawDescData
}

var file_proto_stock_v1_stock_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stock_v1_stock_service_proto_goTypes = []any{
	(*GetStockRequest)(nil),  // 0: proto.stock.v1.GetStockRequest
	(*GetStockResponse)(nil), // 1: proto.stock.v1.GetStockResponse
}
var file_proto_stock_v1_stock_service_proto_depIdxs = []int32{
	0, // 0: proto.stock.v1.StockService.GetStock:input_type -> proto.stock.v1.GetStockRequest
	1, // 1: proto.stock.v1.StockService.GetStock:output_type -> proto.stock.v1.GetStockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stock_v1_stock_service_proto_init() }
func file_proto_stock_v1_stock_service_proto_init() {
	if File_proto_stock_v1_stock_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stock_v1_stock_service_proto_rawDesc), len(file_proto_stock_v1_stock_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stock_v1_stock_service_proto_goTypes,
		DependencyIndexes: file_proto_stock_v1_stock_service_proto_depIdxs,
		MessageInfos:      file_proto_stock_v1_stock_service_proto_msgTypes,
	}.Build()
	File_proto_stock_v1_stock_service_proto = out.File
	file_proto_stock_v1_stock_service_proto_goTypes = nil
	file_proto_stock_v1_stock_service_proto_depIdxs = nil
}
