// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/services/v1/category_service.proto

package servicesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Add category
type AddCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCategoryRequest) Reset() {
	*x = AddCategoryRequest{}
	mi := &file_proto_services_v1_category_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryRequest) ProtoMessage() {}

func (x *AddCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_v1_category_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryRequest.ProtoReflect.Descriptor instead.
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_v1_category_service_proto_rawDescGZIP(), []int{0}
}

type AddCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCategoryResponse) Reset() {
	*x = AddCategoryResponse{}
	mi := &file_proto_services_v1_category_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryResponse) ProtoMessage() {}

func (x *AddCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_v1_category_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryResponse.ProtoReflect.Descriptor instead.
func (*AddCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_v1_category_service_proto_rawDescGZIP(), []int{1}
}

// Update category
type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_proto_services_v1_category_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_v1_category_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_v1_category_service_proto_rawDescGZIP(), []int{2}
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_proto_services_v1_category_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_v1_category_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_v1_category_service_proto_rawDescGZIP(), []int{3}
}

var File_proto_services_v1_category_service_proto protoreflect.FileDescriptor

const file_proto_services_v1_category_service_proto_rawDesc = "" +
	"\n" +
	"(proto/services/v1/category_service.proto\x12\x11proto.services.v1\"\x14\n" +
	"\x12AddCategoryRequest\"\x15\n" +
	"\x13AddCategoryResponse\"\x17\n" +
	"\x15UpdateCategoryRequest\"\x18\n" +
	"\x16UpdateCategoryResponse2\xd6\x01\n" +
	"\x0fCategoryService\x12\\\n" +
	"\vAddCategory\x12%.proto.services.v1.AddCategoryRequest\x1a&.proto.services.v1.AddCategoryResponse\x12e\n" +
	"\x0eUpdateCategory\x12(.proto.services.v1.UpdateCategoryRequest\x1a).proto.services.v1.UpdateCategoryResponseB\xdf\x01\n" +
	"\x15com.proto.services.v1B\x14CategoryServiceProtoP\x01ZJgithub.com/DarylvdBerg/stock-o-matic/internal/proto/services/v1;servicesv1\xa2\x02\x03PSX\xaa\x02\x11Proto.Services.V1\xca\x02\x11Proto\\Services\\V1\xe2\x02\x1dProto\\Services\\V1\\GPBMetadata\xea\x02\x13Proto::Services::V1b\x06proto3"

var (
	file_proto_services_v1_category_service_proto_rawDescOnce sync.Once
	file_proto_services_v1_category_service_proto_rawDescData []byte
)

func file_proto_services_v1_category_service_proto_rawDescGZIP() []byte {
	file_proto_services_v1_category_service_proto_rawDescOnce.Do(func() {
		file_proto_services_v1_category_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_v1_category_service_proto_rawDesc), len(file_proto_services_v1_category_service_proto_rawDesc)))
	})
	return file_proto_services_v1_category_service_proto_rawDescData
}

var file_proto_services_v1_category_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_services_v1_category_service_proto_goTypes = []any{
	(*AddCategoryRequest)(nil),     // 0: proto.services.v1.AddCategoryRequest
	(*AddCategoryResponse)(nil),    // 1: proto.services.v1.AddCategoryResponse
	(*UpdateCategoryRequest)(nil),  // 2: proto.services.v1.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil), // 3: proto.services.v1.UpdateCategoryResponse
}
var file_proto_services_v1_category_service_proto_depIdxs = []int32{
	0, // 0: proto.services.v1.CategoryService.AddCategory:input_type -> proto.services.v1.AddCategoryRequest
	2, // 1: proto.services.v1.CategoryService.UpdateCategory:input_type -> proto.services.v1.UpdateCategoryRequest
	1, // 2: proto.services.v1.CategoryService.AddCategory:output_type -> proto.services.v1.AddCategoryResponse
	3, // 3: proto.services.v1.CategoryService.UpdateCategory:output_type -> proto.services.v1.UpdateCategoryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_services_v1_category_service_proto_init() }
func file_proto_services_v1_category_service_proto_init() {
	if File_proto_services_v1_category_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_v1_category_service_proto_rawDesc), len(file_proto_services_v1_category_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_v1_category_service_proto_goTypes,
		DependencyIndexes: file_proto_services_v1_category_service_proto_depIdxs,
		MessageInfos:      file_proto_services_v1_category_service_proto_msgTypes,
	}.Build()
	File_proto_services_v1_category_service_proto = out.File
	file_proto_services_v1_category_service_proto_goTypes = nil
	file_proto_services_v1_category_service_proto_depIdxs = nil
}
