syntax = "proto3";

package proto.services.v1;

import "proto/core/v1/stock.proto";

option go_package = "proto/services/v1";

service CategoryService {
  rpc GetCategories(GetCategoriesRequest) returns (GetCategoriesResponse);
  rpc AddCategory(AddCategoryRequest) returns (AddCategoryResponse);
  rpc UpdateCategory(UpdateCategoryRequest) returns (UpdateCategoryResponse);
  rpc DeleteCategory(DeleteCategoryRequest) returns (DeleteCategoryResponse);
}

// Get categories
message GetCategoriesRequest {}
message GetCategoriesResponse {
  repeated core.v1.Category categories = 1;
}

// Add category
message AddCategoryRequest {
  core.v1.Category category = 1;
}
message AddCategoryResponse {}

// Update category
message UpdateCategoryRequest {
  uint32 id = 1;
  string name = 2;
  bool monitor_stock = 3;
}
message UpdateCategoryResponse {}

// Delete category
message DeleteCategoryRequest {
  uint32 id = 1;
}
message DeleteCategoryResponse {}
