// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/stock/v1/stock_service.proto

package stockv1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/DarylvdBerg/stock-o-matic/internal/proto/stock/v1"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// StockServiceName is the fully-qualified name of the StockService service.
	StockServiceName = "proto.stock.v1.StockService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StockServiceGetStockProcedure is the fully-qualified name of the StockService's GetStock RPC.
	StockServiceGetStockProcedure = "/proto.stock.v1.StockService/GetStock"
)

// StockServiceClient is a client for the proto.stock.v1.StockService service.
type StockServiceClient interface {
	GetStock(context.Context, *connect_go.Request[v1.GetStockRequest]) (*connect_go.Response[v1.GetStockResponse], error)
}

// NewStockServiceClient constructs a client for the proto.stock.v1.StockService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStockServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) StockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &stockServiceClient{
		getStock: connect_go.NewClient[v1.GetStockRequest, v1.GetStockResponse](
			httpClient,
			baseURL+StockServiceGetStockProcedure,
			opts...,
		),
	}
}

// stockServiceClient implements StockServiceClient.
type stockServiceClient struct {
	getStock *connect_go.Client[v1.GetStockRequest, v1.GetStockResponse]
}

// GetStock calls proto.stock.v1.StockService.GetStock.
func (c *stockServiceClient) GetStock(ctx context.Context, req *connect_go.Request[v1.GetStockRequest]) (*connect_go.Response[v1.GetStockResponse], error) {
	return c.getStock.CallUnary(ctx, req)
}

// StockServiceHandler is an implementation of the proto.stock.v1.StockService service.
type StockServiceHandler interface {
	GetStock(context.Context, *connect_go.Request[v1.GetStockRequest]) (*connect_go.Response[v1.GetStockResponse], error)
}

// NewStockServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStockServiceHandler(svc StockServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	stockServiceGetStockHandler := connect_go.NewUnaryHandler(
		StockServiceGetStockProcedure,
		svc.GetStock,
		opts...,
	)
	return "/proto.stock.v1.StockService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StockServiceGetStockProcedure:
			stockServiceGetStockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStockServiceHandler struct{}

func (UnimplementedStockServiceHandler) GetStock(context.Context, *connect_go.Request[v1.GetStockRequest]) (*connect_go.Response[v1.GetStockResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.stock.v1.StockService.GetStock is not implemented"))
}
