// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/services/v1/category_service.proto

package servicesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/DarylvdBerg/stock-o-matic/internal/proto/services/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CategoryServiceName is the fully-qualified name of the CategoryService service.
	CategoryServiceName = "proto.services.v1.CategoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CategoryServiceAddCategoryProcedure is the fully-qualified name of the CategoryService's
	// AddCategory RPC.
	CategoryServiceAddCategoryProcedure = "/proto.services.v1.CategoryService/AddCategory"
	// CategoryServiceUpdateCategoryProcedure is the fully-qualified name of the CategoryService's
	// UpdateCategory RPC.
	CategoryServiceUpdateCategoryProcedure = "/proto.services.v1.CategoryService/UpdateCategory"
)

// CategoryServiceClient is a client for the proto.services.v1.CategoryService service.
type CategoryServiceClient interface {
	AddCategory(context.Context, *v1.AddCategoryRequest) (*v1.AddCategoryResponse, error)
	UpdateCategory(context.Context, *v1.UpdateCategoryRequest) (*v1.UpdateCategoryResponse, error)
}

// NewCategoryServiceClient constructs a client for the proto.services.v1.CategoryService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCategoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CategoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	categoryServiceMethods := v1.File_proto_services_v1_category_service_proto.Services().ByName("CategoryService").Methods()
	return &categoryServiceClient{
		addCategory: connect.NewClient[v1.AddCategoryRequest, v1.AddCategoryResponse](
			httpClient,
			baseURL+CategoryServiceAddCategoryProcedure,
			connect.WithSchema(categoryServiceMethods.ByName("AddCategory")),
			connect.WithClientOptions(opts...),
		),
		updateCategory: connect.NewClient[v1.UpdateCategoryRequest, v1.UpdateCategoryResponse](
			httpClient,
			baseURL+CategoryServiceUpdateCategoryProcedure,
			connect.WithSchema(categoryServiceMethods.ByName("UpdateCategory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// categoryServiceClient implements CategoryServiceClient.
type categoryServiceClient struct {
	addCategory    *connect.Client[v1.AddCategoryRequest, v1.AddCategoryResponse]
	updateCategory *connect.Client[v1.UpdateCategoryRequest, v1.UpdateCategoryResponse]
}

// AddCategory calls proto.services.v1.CategoryService.AddCategory.
func (c *categoryServiceClient) AddCategory(ctx context.Context, req *v1.AddCategoryRequest) (*v1.AddCategoryResponse, error) {
	response, err := c.addCategory.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateCategory calls proto.services.v1.CategoryService.UpdateCategory.
func (c *categoryServiceClient) UpdateCategory(ctx context.Context, req *v1.UpdateCategoryRequest) (*v1.UpdateCategoryResponse, error) {
	response, err := c.updateCategory.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CategoryServiceHandler is an implementation of the proto.services.v1.CategoryService service.
type CategoryServiceHandler interface {
	AddCategory(context.Context, *v1.AddCategoryRequest) (*v1.AddCategoryResponse, error)
	UpdateCategory(context.Context, *v1.UpdateCategoryRequest) (*v1.UpdateCategoryResponse, error)
}

// NewCategoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCategoryServiceHandler(svc CategoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	categoryServiceMethods := v1.File_proto_services_v1_category_service_proto.Services().ByName("CategoryService").Methods()
	categoryServiceAddCategoryHandler := connect.NewUnaryHandlerSimple(
		CategoryServiceAddCategoryProcedure,
		svc.AddCategory,
		connect.WithSchema(categoryServiceMethods.ByName("AddCategory")),
		connect.WithHandlerOptions(opts...),
	)
	categoryServiceUpdateCategoryHandler := connect.NewUnaryHandlerSimple(
		CategoryServiceUpdateCategoryProcedure,
		svc.UpdateCategory,
		connect.WithSchema(categoryServiceMethods.ByName("UpdateCategory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.services.v1.CategoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CategoryServiceAddCategoryProcedure:
			categoryServiceAddCategoryHandler.ServeHTTP(w, r)
		case CategoryServiceUpdateCategoryProcedure:
			categoryServiceUpdateCategoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCategoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCategoryServiceHandler struct{}

func (UnimplementedCategoryServiceHandler) AddCategory(context.Context, *v1.AddCategoryRequest) (*v1.AddCategoryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.services.v1.CategoryService.AddCategory is not implemented"))
}

func (UnimplementedCategoryServiceHandler) UpdateCategory(context.Context, *v1.UpdateCategoryRequest) (*v1.UpdateCategoryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.services.v1.CategoryService.UpdateCategory is not implemented"))
}
