// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/services/v1/stock_service.proto

package servicesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/DarylvdBerg/stock-o-matic/internal/proto/services/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StockServiceName is the fully-qualified name of the StockService service.
	StockServiceName = "proto.services.v1.StockService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StockServiceGetStockProcedure is the fully-qualified name of the StockService's GetStock RPC.
	StockServiceGetStockProcedure = "/proto.services.v1.StockService/GetStock"
	// StockServiceAddStockProcedure is the fully-qualified name of the StockService's AddStock RPC.
	StockServiceAddStockProcedure = "/proto.services.v1.StockService/AddStock"
	// StockServiceUpdateStockProcedure is the fully-qualified name of the StockService's UpdateStock
	// RPC.
	StockServiceUpdateStockProcedure = "/proto.services.v1.StockService/UpdateStock"
)

// StockServiceClient is a client for the proto.services.v1.StockService service.
type StockServiceClient interface {
	GetStock(context.Context, *v1.GetStockRequest) (*v1.GetStockResponse, error)
	AddStock(context.Context, *v1.AddStockRequest) (*v1.AddStockResponse, error)
	UpdateStock(context.Context, *v1.UpdateStockRequest) (*v1.UpdateStockResponse, error)
}

// NewStockServiceClient constructs a client for the proto.services.v1.StockService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStockServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stockServiceMethods := v1.File_proto_services_v1_stock_service_proto.Services().ByName("StockService").Methods()
	return &stockServiceClient{
		getStock: connect.NewClient[v1.GetStockRequest, v1.GetStockResponse](
			httpClient,
			baseURL+StockServiceGetStockProcedure,
			connect.WithSchema(stockServiceMethods.ByName("GetStock")),
			connect.WithClientOptions(opts...),
		),
		addStock: connect.NewClient[v1.AddStockRequest, v1.AddStockResponse](
			httpClient,
			baseURL+StockServiceAddStockProcedure,
			connect.WithSchema(stockServiceMethods.ByName("AddStock")),
			connect.WithClientOptions(opts...),
		),
		updateStock: connect.NewClient[v1.UpdateStockRequest, v1.UpdateStockResponse](
			httpClient,
			baseURL+StockServiceUpdateStockProcedure,
			connect.WithSchema(stockServiceMethods.ByName("UpdateStock")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stockServiceClient implements StockServiceClient.
type stockServiceClient struct {
	getStock    *connect.Client[v1.GetStockRequest, v1.GetStockResponse]
	addStock    *connect.Client[v1.AddStockRequest, v1.AddStockResponse]
	updateStock *connect.Client[v1.UpdateStockRequest, v1.UpdateStockResponse]
}

// GetStock calls proto.services.v1.StockService.GetStock.
func (c *stockServiceClient) GetStock(ctx context.Context, req *v1.GetStockRequest) (*v1.GetStockResponse, error) {
	response, err := c.getStock.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AddStock calls proto.services.v1.StockService.AddStock.
func (c *stockServiceClient) AddStock(ctx context.Context, req *v1.AddStockRequest) (*v1.AddStockResponse, error) {
	response, err := c.addStock.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateStock calls proto.services.v1.StockService.UpdateStock.
func (c *stockServiceClient) UpdateStock(ctx context.Context, req *v1.UpdateStockRequest) (*v1.UpdateStockResponse, error) {
	response, err := c.updateStock.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// StockServiceHandler is an implementation of the proto.services.v1.StockService service.
type StockServiceHandler interface {
	GetStock(context.Context, *v1.GetStockRequest) (*v1.GetStockResponse, error)
	AddStock(context.Context, *v1.AddStockRequest) (*v1.AddStockResponse, error)
	UpdateStock(context.Context, *v1.UpdateStockRequest) (*v1.UpdateStockResponse, error)
}

// NewStockServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStockServiceHandler(svc StockServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stockServiceMethods := v1.File_proto_services_v1_stock_service_proto.Services().ByName("StockService").Methods()
	stockServiceGetStockHandler := connect.NewUnaryHandlerSimple(
		StockServiceGetStockProcedure,
		svc.GetStock,
		connect.WithSchema(stockServiceMethods.ByName("GetStock")),
		connect.WithHandlerOptions(opts...),
	)
	stockServiceAddStockHandler := connect.NewUnaryHandlerSimple(
		StockServiceAddStockProcedure,
		svc.AddStock,
		connect.WithSchema(stockServiceMethods.ByName("AddStock")),
		connect.WithHandlerOptions(opts...),
	)
	stockServiceUpdateStockHandler := connect.NewUnaryHandlerSimple(
		StockServiceUpdateStockProcedure,
		svc.UpdateStock,
		connect.WithSchema(stockServiceMethods.ByName("UpdateStock")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.services.v1.StockService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StockServiceGetStockProcedure:
			stockServiceGetStockHandler.ServeHTTP(w, r)
		case StockServiceAddStockProcedure:
			stockServiceAddStockHandler.ServeHTTP(w, r)
		case StockServiceUpdateStockProcedure:
			stockServiceUpdateStockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStockServiceHandler struct{}

func (UnimplementedStockServiceHandler) GetStock(context.Context, *v1.GetStockRequest) (*v1.GetStockResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.services.v1.StockService.GetStock is not implemented"))
}

func (UnimplementedStockServiceHandler) AddStock(context.Context, *v1.AddStockRequest) (*v1.AddStockResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.services.v1.StockService.AddStock is not implemented"))
}

func (UnimplementedStockServiceHandler) UpdateStock(context.Context, *v1.UpdateStockRequest) (*v1.UpdateStockResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.services.v1.StockService.UpdateStock is not implemented"))
}
