// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/stock-o-matic-api/category/repository.go
//
// Generated by this command:
//
//	mockgen -source=cmd/stock-o-matic-api/category/repository.go -destination=cmd/stock-o-matic-api/tests/mocks/category/category_repository.go
//

// Package mock_category is a generated GoMock package.
package mock_category

import (
	context "context"
	reflect "reflect"

	corev1 "github.com/DarylvdBerg/stock-o-matic/internal/proto/core/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockIRepository) AddCategory(ctx context.Context, data *corev1.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockIRepositoryMockRecorder) AddCategory(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockIRepository)(nil).AddCategory), ctx, data)
}

// GetCategories mocks base method.
func (m *MockIRepository) GetCategories(ctx context.Context) ([]*corev1.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx)
	ret0, _ := ret[0].([]*corev1.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockIRepositoryMockRecorder) GetCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockIRepository)(nil).GetCategories), ctx)
}

// UpdateCategory mocks base method.
func (m *MockIRepository) UpdateCategory(ctx context.Context, id uint32, name string) (*corev1.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, id, name)
	ret0, _ := ret[0].(*corev1.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockIRepositoryMockRecorder) UpdateCategory(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockIRepository)(nil).UpdateCategory), ctx, id, name)
}
